CREATE OR REPLACE TABLE star_schema.fact_accident (
    ACCIDENT_NO STRING PRIMARY KEY,
    ACCIDENTDATE DATE,
    ACCIDENTTIME TIME,
    ACCIDENT_TYPE INTEGER REFERENCES star_schema.accident_type_dim(ACCIDENT_TYPE),
    DAY_OF_WEEK INTEGER,
    LIGHT_CONDITION INTEGER REFERENCES star_schema.light_condition_dim(LIGHT_CONDITION),
    NO_OF_VEHICLES INTEGER,
    NO_PERSONS INTEGER,
    NO_PERSONS_KILLED INTEGER,
    SEVERITY INTEGER,
    SPEED_ZONE INTEGER
);

CREATE OR REPLACE TABLE star_schema.dim_vehicle (
    VEHICLE_ID STRING PRIMARY KEY,
    ACCIDENT_NO STRING REFERENCES star_schema.accident_fact(ACCIDENT_NO),
    VEHICLE_YEAR_MANUF INTEGER,
    INITIAL_DIRECTION STRING,
    ROAD_SURFACE_TYPE INTEGER REFERENCES star_schema.road_surface_type_dim(ROAD_SURFACE_TYPE),
    VEHICLE_BODY_STYLE STRING,
    VEHICLE_MAKE STRING,
    VEHICLE_MODEL STRING,
    VEHICLE_TYPE INTEGER REFERENCES star_schema.vehicle_type_dim(VEHICLE_TYPE),
    TARE_WEIGHT INTEGER,
    TOTAL_NO_OCCUPANTS INTEGER,
    LEVEL_OF_DAMAGE INTEGER,
    OWNER_POSTCODE INTEGER
);

CREATE OR REPLACE TABLE star_schema.dim_accident_type (
    ACCIDENT_TYPE INTEGER PRIMARY KEY,
    ACCIDENT_TYPE_DESC STRING
);

CREATE OR REPLACE TABLE star_schema.dim_light_condition (
    LIGHT_CONDITION INTEGER PRIMARY KEY,
    LIGHT_CONDITION_DESC STRING
);


CREATE OR REPLACE TABLE star_schema.dim_road_surface_type (
    ROAD_SURFACE_TYPE INTEGER PRIMARY KEY,
    ROAD_SURFACE_TYPE_DESC STRING
);

CREATE OR REPLACE TABLE star_schema.dim_vehicle_type (
    VEHICLE_TYPE INTEGER PRIMARY KEY,
    VEHICLE_TYPE_DESC STRING
);
